/**
 * Created by Roman on 04.04.2015.
 */
module.exports = (function () {
    require('./birthday.js');
    require('./campaign.js');
    require('./customer.js');
    require('./degree.js');
    require('./deliverTo.js');
    require('./department.js');
    require('./destination.js');
    require('./personnel.js');
    require('./position.js');
    require('./jobType.js');
    require('./incoterm.js');
    require('./industry.js');
    require('./invoicingControl.js');
    require('./language.js');
    require('./module.js');
    require('./nationality.js');
    require('./opportunitie.js');
    require('./payment.js');
    require('./paymentMethod.js');
    require('./paymentTerm.js');
    require('./priority.js');
    require('./period.js');
    require('./item.js');
    require('./category.js');
    require('./productTypes.js');
    require('./profile.js');
    require('./objective.js');
    require('./projectType.js');
    require('./quotation.js');
    require('./relatedStatus.js');
    require('./source.js');
    require('./saas.js');
    require('./salary.js');
    require('./salaryCash.js');
    require('./task.js');
    require('./user.js');
    require('./invoice.js');
    require('./workflow.js');
    require('./wTrack.js');
    require('./wTrackInvoice.js');
    require('./wTrackPayment.js');
    require('./monthHours.js');
    require('./holiday.js');
    require('./vacation.js');
    require('./bonusType.js');
    require('./savedFilters.js');

    require('./country');
})();